CREATE OR REPLACE FUNCTION FNC_GET_STATUT_PAIEMENT (
    p_facture_id IN NUMBER
)
RETURN VARCHAR2
AS
    v_statut_paiement FACTURE.STATUT_PAIEMENT%TYPE;
BEGIN
    SELECT STATUT_PAIEMENT
    INTO v_statut_paiement
    FROM FACTURE
    WHERE FACTURE_ID = p_facture_id;

    RETURN v_statut_paiement;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'FACTURE INEXISTANTE';
    WHEN OTHERS THEN
        RAISE;
END FNC_GET_STATUT_PAIEMENT;
/