CREATE OR REPLACE TRIGGER TRG_LIGNE_FACTURE_MONT_PART
BEFORE INSERT OR UPDATE OF PRIX_UNITAIRE, QUANTITE ON LIGNE_FACTURE
FOR EACH ROW
BEGIN
    -- Calculer le Montant Partiel = Prix Unitaire * Quantité
    :NEW.MONTANT_PARTIEL := :NEW.PRIX_UNITAIRE * :NEW.QUANTITE;
END  TRG_LIGNE_FACTURE_MONT_PART ;
/