CREATE OR REPLACE TRIGGER T_AUDIT_RESERVATION
AFTER UPDATE ON RESERVATION
FOR EACH ROW
BEGIN
    IF :OLD.STATUT <> :NEW.STATUT OR :OLD.DATE_DEBUT <> :NEW.DATE_DEBUT THEN
        INSERT INTO SYSTEM_AUDIT (AUDIT_ID, TABLENAME, ACTION, OLDVALUE, NEWVALUE, TIMESTAMP)
        VALUES (AUDIT_SEQ.NEXTVAL, 'RESERVATION', 'Modif Res ' || :NEW.RES_ID,
        'St: ' || :OLD.STATUT || ' D: ' || :OLD.DATE_DEBUT,
        'St: ' || :NEW.STATUT || ' D: ' || :NEW.DATE_DEBUT, SYSDATE);
    END IF;
END;
/